# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: search_service.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    AsyncIterator,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class Product(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    quantity: int = betterproto.int32_field(4)
    unit: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class SearchRequest(betterproto.Message):
    job_id: str = betterproto.string_field(1)
    products: List["Product"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AnalysisRecord(betterproto.Message):
    candidate_url: str = betterproto.string_field(1)
    candidate_name: str = betterproto.string_field(2)
    matched: bool = betterproto.bool_field(3)
    confidence: float = betterproto.float_field(4)
    reason: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class MatchResult(betterproto.Message):
    product_id: str = betterproto.string_field(1)
    matched: bool = betterproto.bool_field(2)
    etm_url: str = betterproto.string_field(3)
    etm_name: str = betterproto.string_field(4)
    etm_price: float = betterproto.float_field(5)
    etm_sku: str = betterproto.string_field(6)
    confidence: float = betterproto.float_field(7)
    ai_reasoning: str = betterproto.string_field(8)
    ai_analyses: List["AnalysisRecord"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class CancelJobRequest(betterproto.Message):
    job_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CancelJobResponse(betterproto.Message):
    was_running: bool = betterproto.bool_field(1)


class SearchServiceStub(betterproto.ServiceStub):
    async def search_products(
        self,
        search_request: "SearchRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[MatchResult]:
        async for response in self._unary_stream(
            "/tendermate.agent.v1.SearchService/SearchProducts",
            search_request,
            MatchResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def cancel_job(
        self,
        cancel_job_request: "CancelJobRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CancelJobResponse":
        return await self._unary_unary(
            "/tendermate.agent.v1.SearchService/CancelJob",
            cancel_job_request,
            CancelJobResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SearchServiceBase(ServiceBase):

    async def search_products(
        self, search_request: "SearchRequest"
    ) -> AsyncIterator[MatchResult]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield MatchResult()

    async def cancel_job(
        self, cancel_job_request: "CancelJobRequest"
    ) -> "CancelJobResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_search_products(
        self, stream: "grpclib.server.Stream[SearchRequest, MatchResult]"
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.search_products,
            stream,
            request,
        )

    async def __rpc_cancel_job(
        self, stream: "grpclib.server.Stream[CancelJobRequest, CancelJobResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cancel_job(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/tendermate.agent.v1.SearchService/SearchProducts": grpclib.const.Handler(
                self.__rpc_search_products,
                grpclib.const.Cardinality.UNARY_STREAM,
                SearchRequest,
                MatchResult,
            ),
            "/tendermate.agent.v1.SearchService/CancelJob": grpclib.const.Handler(
                self.__rpc_cancel_job,
                grpclib.const.Cardinality.UNARY_UNARY,
                CancelJobRequest,
                CancelJobResponse,
            ),
        }
